constrain rubocop version for 2.5 support
Versions of RuboCop later than 1.28 report:

> Error: RuboCop found unsupported Ruby version 2.5 in
> `TargetRubyVersion` parameter (in .rubocop.yml). 2.5-compatible analysis
> was dropped after version 1.28. Supported versions: 2.6, 2.7, 3.0, 3.1,
> 3.2

because 2.5 is EOL and no longer supported.